<?php

/**
 * @file
 * Contains appointments.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function appointments_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the appointments module.
    case 'help.page.appointments':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for creating appointments') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function appointments_theme() {
  return [
    'appointments' => [
      'render element' => 'children',
    ],
  ];
}
